language: php
php:
  - 5.4
  - 5.5
  - 5.6
addons:
  postgresql: "9.3"
before_script:
  - composer update
  - psql -U postgres -c 'create database test;'
  - psql -U postgres -d test -c "create extension hstore;"
script: phpunit -c phpunit.xml